apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qbb16kz2e-dotnet-basic
  janus-idp.io/tekton: qbb16kz2e-dotnet-basic
  backstage.io/kubernetes-id: qbb16kz2e-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qbb16kz2e-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
